Repository bit-bots/bitbots_vision, pull requests merged in 2019-09, with the labels that each got.

#95 Prevent publishing of None confidences
  bitbots_vision/src/bitbots_vision/vision_modules/ros_utils.py
Labels: bug

#94 Fix ball offset
  bitbots_vision/src/bitbots_vision/vision_modules/field_boundary.py
Labels: bug

#106 Handle tf connectivity exceptions
  bitbots_vision/src/bitbots_vision/vision_modules/field_boundary.py
Labels: bug

#105 Fix reconfiguration of dynamic color space
  bitbots_vision/src/bitbots_vision/vision.py
Labels: bug

#117 Fix vision cfg
  bitbots_vision/cfg/Vision.cfg
Labels: bug

#119 bitbots_vision: fix goal message and logwarn
  bitbots_vision/src/bitbots_vision/dynamic_color_space.py
  bitbots_vision/src/bitbots_vision/vision.py
Labels: bug

#122 Refactor: underscores for private class methods and variables
  bitbots_vision/src/bitbots_vision/dynamic_color_space.py
  bitbots_vision/src/bitbots_vision/vision.py
  bitbots_vision/src/bitbots_vision/vision_modules/candidate.py
  bitbots_vision/src/bitbots_vision/vision_modules/color.py
  bitbots_vision/src/bitbots_vision/vision_modules/debug.py
  bitbots_vision/src/bitbots_vision/vision_modules/evaluator.py
  bitbots_vision/src/bitbots_vision/vision_modules/fcnn_handler.py
  bitbots_vision/src/bitbots_vision/vision_modules/field_boundary.py
  bitbots_vision/src/bitbots_vision/vision_modules/live_fcnn_03.py
  bitbots_vision/src/bitbots_vision/vision_modules/obstacle.py
  bitbots_vision/src/bitbots_vision/vision_modules/yolo_handler.py
Labels: help wanted, question

#118 Add auto build for vision extensions
  bitbots_vision/CMakeLists.txt
Labels: feature

#128 Fix issue with the private variable refactoring
  bitbots_vision/src/bitbots_vision/vision_modules/yolo_handler.py
Labels: bug, high priority

#127 New doc system
  .gitignore
  README.md
  bitbots_vision/CMakeLists.txt
  bitbots_vision/docs/_static/logo.png
  bitbots_vision/docs/index.rst
  bitbots_vision/docs/pyapi/bitbots_vision.rst
  bitbots_vision/docs/pyapi/bitbots_vision.vision_modules.legacy.rst
  bitbots_vision/docs/pyapi/bitbots_vision.vision_modules.rst
  bitbots_vision/docs/pyapi/modules.rst
  bitbots_vision/package.xml
  bitbots_vision/src/bitbots_vision/vision_modules/candidate.py
  bitbots_vision/src/bitbots_vision/vision_modules/debug.py
  bitbots_vision/src/bitbots_vision/vision_modules/dummy_ballfinder.py
  bitbots_vision/src/bitbots_vision/vision_modules/evaluator.py
  bitbots_vision/src/bitbots_vision/vision_modules/fcnn_handler.py
  bitbots_vision/src/bitbots_vision/vision_modules/field_boundary.py
  bitbots_vision/src/bitbots_vision/vision_modules/lines.py
  bitbots_vision/src/bitbots_vision/vision_modules/obstacle.py
  bitbots_vision/src/bitbots_vision/vision_modules/yolo_handler.py
Labels: enhancement, feature
