Repository bit-bots/bitbots_vision, pull requests merged in 2020-03, with the labels that each got.

#206 white_balancer: Update cfg py version
  white_balancer/cfg/WhiteBalancer.cfg
  white_balancer/package.xml
Labels: bug

#205 Line LUTs
  bitbots_vision/cfg/Vision.cfg
  bitbots_vision/config/color_spaces/basler_f031_lines.pickle
  bitbots_vision/config/visionparams.yaml
  bitbots_vision/package.xml
  bitbots_vision/src/bitbots_vision/vision.py
  bitbots_vision/src/bitbots_vision/vision_modules/color.py
  bitbots_vision/src/bitbots_vision/vision_modules/lines.py
  bitbots_vision/src/bitbots_vision/vision_modules/ros_utils.py
Labels: feature

#208 Fix dyn reconf enums
  bitbots_vision/config/visionparams.yaml
  bitbots_vision/package.xml
  bitbots_vision/src/bitbots_vision/vision_modules/ros_utils.py
Labels: bug

#214 Add a CI bagde
  README.md
Labels: enhancement, low priority
